### ISSUE TITLE
view documents_shared_with_user not work.

### ISSUE THREAD

**Issue by Talentaa** [pierre-lgb/slashwriter#7]
In page shares, when I click `Shared with me`, there is nothing.
When I click `My shares`, it work well.

But I am sure that somebody does share a doc with me.

In your sql `CREATE VIEW documents_shared_with_user`, I found it may  wrong at this
`(CASE 
            WHEN s.user_permissions ? auth.uid()::text THEN 
                s.user_permissions->>auth.uid()::text
            ELSE 
                NULL
        END) AS permission,`
when I use a real uuid text like `'b805f4c4-ad88-4487-bda1-29a5b1af857d'` to replace `auth.uid()::text`, it return something I need.

Your website seems to have this issue too.

I run it locally, everything except `documents_shared_with_user` works fine.

Can you tell me what happend.

**Comment by pierre-lgb** [comment]
Hi,

A few days ago, I had to pause the supabase backend because it reached the free plan limitations. So the demo website no longer works.

When you ran it locally, did you setup your own supabase instance, and is the user who shared a document with you stored on the same supabase instance ?

**Comment by Talentaa** [comment]
> Hi,
> 
> A few days ago, I had to pause the supabase backend because it reached the free plan limitations. So the demo website no longer works.
> 
> When you ran it locally, did you setup your own supabase instance, and is the user who shared a document with you stored on the same supabase instance ?

I run supabase on cloud.  This website.
https://supabase.com/dashboard/projects 

I created two users, each user shared a document with the other.
User A has a doc that gives a edit permission to User B `b805f4c4-ad88-4487-bda1-29a5b1af857d`
Like in the picture below
![image](https://github.com/pierre-lgb/slashwriter/assets/60936055/b1befaa2-7eb0-4301-bf9d-2f41728ca6b3)

Back to User B, Shared with me has nothing
![image](https://github.com/pierre-lgb/slashwriter/assets/60936055/665c6b25-a96a-4e7b-9ceb-242deaa17a2f)

My shares have a doc that I give a edit permission to User A 
![image](https://github.com/pierre-lgb/slashwriter/assets/60936055/3b691fab-e316-4264-ab8e-22fb29d6eb3c)

In User A's "Shared with me", there is still nothing.

When I open devtools
I found this request return nothing
 `https://*********pjawcx.supabase.co/rest/v1/documents_shared_with_user?select=*`
and this request return something expected
`https://*********pjawcx.supabase.co/rest/v1/documents_shared_by_user?select=*`

So I think there's something wrong with View `documents_shared_with_user`

**Comment by pierre-lgb** [comment]
On your last screenshot, the document visibility is set to `Private` but it should be `Public` based on the settings on your first screenshot. So I don't think the issue comes from the View `documents_shared_with_user`. However this is really weird because I cannot reproduce the issue by following the same steps you described.

When you update the share settings, is the `share` item correctly updated in the database ? For example, if you set the "Anyone with the link" permission to "Can read", do you see this in the database ?
![image](https://github.com/pierre-lgb/slashwriter/assets/83542054/d1b170f7-f290-4383-92a7-dcbe36c65027)

**Comment by Talentaa** [comment]
Sorry, my statement may be wrong.

I want to know how to display some documents in `Shared with me`, because no matter how I set the permissions for the documents, I can't see anything. Like the second screenshot above, it always shows `No element found.`

If your `Shared with me` doesn't show `No element found.`, but some documents, can you provide a screenshot?

If you still can't reproduce it, there may be a problem with my operation. Sorry for wasting your time.

This project is excellent and has inspired me a lot.

**Comment by pierre-lgb** [comment]
My bad, I was actually able to reproduce the issue, you were right.

There was indeed an issue with the View `documents_shared_with_user`, it was created with `security_invoker`, so it wasn't able to access the share settings as they are protected with RLS.

It should solve the issue if you run the following query in the SQL Editor of supabase dashboard:
```sql
ALTER VIEW documents_shared_with_user SET (security_invoker = off);
```

Thank you for reporting the issue, it was very clear and very helpful. I will update the code very soon.

> This project is excellent and has inspired me a lot.

I'm glad you like this project and that it inspires you for your own projects :)
