### ISSUE TITLE
Demo doesn't work, can't login

### ISSUE THREAD

**Issue by shitou333111** [pierre-lgb/slashwriter#9]
When try demo at https://slashwriter.fly.dev/ , It shows: You do not have access to this document.
So I sign up, but it failed to fetch:
![image](https://github.com/pierre-lgb/slashwriter/assets/32065299/3f70ad00-2334-4553-9361-58e569c81584)

**Comment by pierre-lgb** [comment]
Hi, thanks for reaching out,

The demo was indeed not working, because I had to pause the supabase project after it reached its limitations (I am on the free plan). I just restored it, so you should be able to try the demo now :)

Have a nice day!
